# Generated by Django 2.2.3 on 2019-07-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StickerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20)),
                ('item_userstickerset', models.FileField(upload_to='static')),
                ('sticker_title', models.CharField(max_length=20)),
                ('sticker_desc', models.CharField(max_length=200)),
                ('sticker_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'stickerdata_table',
            },
        ),
    ]
