# Generated by Django 2.2.3 on 2019-07-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangostickersmanager', '0002_auto_20190714_1408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyFile',
        ),
        migrations.AddField(
            model_name='stickerdata',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
